create sequence balance_seq start 1 increment 1;
create sequence balance_history_seq start 1 increment 1;
create sequence category_seq start 1 increment 1;
create sequence category_tag_seq start 1 increment 1;
create sequence client_device_seq start 1 increment 1;
create sequence client_event_seq start 1 increment 1;
create sequence client_pref_value_seq start 1 increment 1;
create sequence client_seq start 1 increment 1;
create sequence event_seq start 1 increment 1;
create sequence filial_rate_seq start 1 increment 1;
create sequence filial_seq start 1 increment 1;
create sequence order_product_seq start 1 increment 1;
create sequence orders_seq start 1 increment 1;
create sequence org_bonus_seq start 1 increment 1;
create sequence org_bonus_type_seq start 1 increment 1;
create sequence org_bonus_value_seq start 1 increment 1;
create sequence org_category_seq start 1 increment 1;
create sequence org_image_seq start 1 increment 1;
create sequence org_preference_category_seq start 1 increment 1;
create sequence organization_seq start 1 increment 1;
create sequence preference_category_seq start 1 increment 1;
create sequence purchase_seq start 1 increment 1;
create sequence rate_seq start 1 increment 1;
create sequence raw_material_seq start 1 increment 1;
create sequence role_seq start 1 increment 1;
create sequence sale_seq start 1 increment 1;
create sequence supplier_seq start 1 increment 1;
create sequence unit_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create table balance (id int8 not null, amount float8, client_id int8 not null, org_bonus_id int8 not null, primary key (id));
create table balance_history (id int8 not null, amount float8, bill varchar(255), created_date timestamp, invoice_amount float8, operation_type varchar(255), balance_id int8 not null, users_id int8 not null, primary key (id));
create table category (id int8 not null, create_date timestamp not null, name varchar(255) not null, update_date timestamp, primary key (id));
create table client (id int8 not null, sex varchar(255), created_date timestamp, first_name varchar(255), image text, last_name varchar(255), locale varchar(255), nationality varchar(255), patronymic varchar(255), personal_code varchar(255), primary key (id));
create table client_device (id int8 not null, imei varchar(255), last_enter_date timestamp, password varchar(255), phone_number varchar(255), status boolean default true, client_id int8 not null, primary key (id));
create table client_event (id int8 not null, created_date timestamp, notification_date timestamp, client_id int8 not null, event_id int8 not null, primary key (id));
create table client_organization (client_id int8 not null, organization_id int8 not null, primary key (client_id, organization_id));
create table client_preference_value (id int8 not null, value int4, client_id int8 not null, organization_id int8 not null, organization_preference_category_id int8 not null, primary key (id));
create table event (id int8 not null, created_date timestamp, date_from timestamp, date_to timestamp, description varchar(255), image text, name varchar(255), organization_id int8 not null, primary key (id));
create table filial (id int8 not null, address varchar(255), average_rate float8, created_date timestamp, description varchar(255), image text, latitude float8, longitude float8, name varchar(255), status boolean default true, organization_id int8 not null, primary key (id));
create table filial_rate (id int8 not null, comment varchar(255), created_date timestamp, rate float8, client_id int8 not null, filial_id int8 not null, organization_id int8 not null, primary key (id));
create table orders (id int8 not null, create_date timestamp not null, deadline_date timestamp not null, orders_status varchar(255), update_date timestamp, client_id int8, organization_id int8, users_id int8, primary key (id));
create table orders_product (id int8 not null, create_date timestamp not null, number_of float8, sum_of float8, update_date timestamp, orders_id int8, raw_material_id int8, primary key (id));
create table org_bonus (id int8 not null, created_date timestamp, deleted_date timestamp, status boolean default true, valid_from timestamp, valid_to timestamp, validity int4, org_bonus_type_id int8 not null, organization_id int8 not null, primary key (id));
create table org_bonus_type (id int8 not null, description varchar(255), name varchar(255), value_type varchar(255), primary key (id));
create table org_bonus_value (id int8 not null, max int4, min int4, value int4, org_bonus_id int8 not null, primary key (id));
create table org_category (id int8 not null, created_date timestamp, description varchar(255), image text, name varchar(255), primary key (id));
create table org_category_tag (org_category_id int8 not null, tag_id int8 not null, primary key (org_category_id, tag_id));
create table org_image (id int8 not null, image text not null, organization_id int8 not null, primary key (id));
create table org_preference_category (id int8 not null, organization_id int8 not null, preference_category_id int8 not null, primary key (id));
create table organization (id int8 not null, created_date timestamp, description varchar(255), image text, name varchar(255), status boolean default true, category_id int8 not null, primary key (id));
create table preference_category (id int8 not null, name varchar(255), type varchar(255), parent_id int8, primary key (id));
create table purchase (id int8 not null, bar_code varchar(255) not null, count int4 not null, create_date timestamp not null, price_for_one float4 not null, publisher varchar(255) not null, summ float4 not null, update_date timestamp, organization_id int8, rate_id int8, raw_material_id int8, primary key (id));
create table rate (id int8 not null, create_date timestamp not null, quantity_in_stock float4 not null, retail_price float4 not null, update_date timestamp, wholesale_price float4 not null, organization_id int8, raw_material_id int8, primary key (id));
create table raw_material (id int8 not null, amount_in_block int4 not null, create_date timestamp not null, description varchar(255) not null, name varchar(255) not null, unit_id int8 not null, update_date timestamp, volume float4 not null, category_id int8, primary key (id));
create table role (id int8 not null, description varchar(255), name varchar(255), primary key (id));
create table sale (id int8 not null, count int4 not null, create_date timestamp not null, orders_id int8 not null, rate_id int8 not null, summ float4 not null, update_date timestamp, primary key (id));
create table supplier (id int8 not null, create_date timestamp not null, name varchar(255) not null, update_date timestamp, primary key (id));
create table tag (id int8 not null, name varchar(255), primary key (id));
create table unit (id int8 not null, create_date timestamp not null, name varchar(255) not null, update_date timestamp, primary key (id));
create table users (id int8 not null, create_date timestamp, password varchar(255) not null, rolenameshort varchar(255), status boolean default true, username varchar(255) not null, organization_id int8, primary key (id));
create table users_roles (users_id int8 not null, roles_id int8 not null, primary key (users_id, roles_id));
alter table balance add constraint FK13o20b873igddbreehug3mxu1 foreign key (client_id) references client;
alter table balance add constraint FKpvfx3lcdihne27fw4vtsfq3uo foreign key (org_bonus_id) references org_bonus;
alter table balance_history add constraint FKh7q28d940m7fkjxasp9fx4cdn foreign key (balance_id) references balance;
alter table balance_history add constraint FKff8ewtc4l1glpdyi6o095llge foreign key (users_id) references users;
alter table client_device add constraint FK5sdhnyeog1gce5acnqpse1bxk foreign key (client_id) references client;
alter table client_event add constraint FK7y6ctrgn2ovkor7ceqa5vlchv foreign key (client_id) references client;
alter table client_event add constraint FKdpm598tqq3wl1fg99obb2wngu foreign key (event_id) references event;
alter table client_organization add constraint FKmebdjayaenowkol0cr6pvhuc8 foreign key (organization_id) references organization;
alter table client_organization add constraint FKtfjeemig9tda2mh2h6a9rngua foreign key (client_id) references client;
alter table client_preference_value add constraint FKi021nym7dx376dgutwg5t75kr foreign key (client_id) references client;
alter table client_preference_value add constraint FKrdajbxkkt1pdtbx1i2k2tcjvh foreign key (organization_id) references organization;
alter table client_preference_value add constraint FKl9aho0mn00grbmxkb3jwvmv5f foreign key (organization_preference_category_id) references org_preference_category;
alter table event add constraint FKkarqc3c84scr3r5ncv5stqbk2 foreign key (organization_id) references organization;
alter table filial add constraint FKs5mv6448op5xhdklmeuwpvlb foreign key (organization_id) references organization;
alter table filial_rate add constraint FKhv9jm6wrdc6hab2b70k2br1dw foreign key (client_id) references client;
alter table filial_rate add constraint FK6bbp1pfbl725jmpm68r6jlge1 foreign key (filial_id) references filial;
alter table filial_rate add constraint FK24rgd72um9941ihv4m63x92k9 foreign key (organization_id) references organization;
alter table orders add constraint FK17yo6gry2nuwg2erwhbaxqbs9 foreign key (client_id) references client;
alter table orders add constraint FKrnfbar8sj4a1s8vfdyakx153d foreign key (organization_id) references organization;
alter table orders add constraint FKe6k45xxoin4fylnwg2jkehwjf foreign key (users_id) references users;
alter table orders_product add constraint FK7h8a805aormf2mxryf70m1n7a foreign key (orders_id) references orders;
alter table orders_product add constraint FKjeh8a7j3vym245rog2l0vqo3e foreign key (raw_material_id) references raw_material;
alter table org_bonus add constraint FKq2d3j7lic0k2d22xqqn2xchxv foreign key (org_bonus_type_id) references org_bonus_type;
alter table org_bonus add constraint FKiuc9fpdvejj7umioyt82lu0pn foreign key (organization_id) references organization;
alter table org_bonus_value add constraint FKeqjrbt7i4wvd36jmchbl6yswv foreign key (org_bonus_id) references org_bonus;
alter table org_category_tag add constraint FKgre9prww05l4itxblcyderxbf foreign key (tag_id) references tag;
alter table org_category_tag add constraint FKs7uiqrfp6nea1d6orry6v0kgs foreign key (org_category_id) references org_category;
alter table org_image add constraint FKt7bsvd3e6kod7ol7271t0ftq7 foreign key (organization_id) references organization;
alter table org_preference_category add constraint FK8eg9mv80rubimvoocrjeli6aj foreign key (organization_id) references organization;
alter table org_preference_category add constraint FK3ioe6em34siocwplvumnpj6jd foreign key (preference_category_id) references preference_category;
alter table organization add constraint FKga36rgp1bkw38qy2uplshwhql foreign key (category_id) references org_category;
alter table preference_category add constraint FKtdv8rj2d2yvqqjmmu715ajc6s foreign key (parent_id) references preference_category;
alter table purchase add constraint FKmaf38iplt9xo2kpdaqb4x37l8 foreign key (organization_id) references organization;
alter table purchase add constraint FKpuc87sx1386rn4yhq0hcuxwfr foreign key (rate_id) references rate;
alter table purchase add constraint FKa7ry1qf6q63mb8lp7dsa6a8mo foreign key (raw_material_id) references raw_material;
alter table rate add constraint FKkn6pf2j86ptiljhdfqspnvr4f foreign key (organization_id) references organization;
alter table rate add constraint FKb3ox4604xblltp0a0cqpocy45 foreign key (raw_material_id) references raw_material;
alter table raw_material add constraint FKpvnmkvnx0nk8pda5mdm20dql9 foreign key (category_id) references category;
alter table raw_material add constraint FK76md1orgum015usg3bwsat9wo foreign key (unit_id) references unit;
alter table sale add constraint FK3tpakjc0024g8ytccrarcpn4d foreign key (orders_id) references orders;
alter table sale add constraint FKgwl3m6th9fufhaokj01pexd60 foreign key (rate_id) references rate;
alter table users add constraint FK9q8fdenwsqjwrjfivd5ovv5k3 foreign key (organization_id) references organization;
alter table users_roles add constraint FK15d410tj6juko0sq9k4km60xq foreign key (roles_id) references role;
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users;